import os
import sys
from flask import Flask, send_from_directory, render_template_string, abort, redirect
from pathlib import Path

# Configuration
DOC_ROOT = Path(".").absolute() # Server is running INSIDE the SSD_DOC root
PORT = 8000

app = Flask(__name__, static_folder=None)

# -----------------------------------------------------------------------------
# Main Dashboard (List all documents)
# -----------------------------------------------------------------------------
@app.route('/')
def index():
    """Show list of available documents in SSD_DOC"""
    if not DOC_ROOT.exists():
        return f"Error: Document root '{DOC_ROOT}' does not exist.", 404
        
    # Scan subdirectories that have 'summary_html/index.html'
    docs = []
    for item in sorted(DOC_ROOT.iterdir()):
        if item.is_dir():
            viewer_path = item / "summary_html" / "index.html"
            if viewer_path.exists():
                docs.append(item.name)
    
    # Simple Dashboard Template
    html = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>SSD Engineering Library</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
        <style>body { font-family: 'Inter', sans-serif; }</style>
    </head>
    <body class="bg-gray-100 h-screen flex items-center justify-center">
        <div class="max-w-4xl w-full p-8">
            <h1 class="text-4xl font-extrabold text-indigo-900 mb-2 tracking-tight">SSD Engineering Library</h1>
            <p class="text-gray-500 mb-10">Select a specification document to view.</p>
            
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {% for doc in docs %}
                <a href="/doc/{{ doc }}/summary_html/index.html" 
                   class="block p-6 bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow border border-gray-200 hover:border-indigo-300 group">
                    <div class="flex items-center justify-between mb-4">
                        <span class="bg-indigo-100 text-indigo-700 text-xs font-bold px-2 py-1 rounded-md uppercase">SPEC</span>
                        <svg class="w-5 h-5 text-gray-400 group-hover:text-indigo-500 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
                    </div>
                    <h2 class="text-xl font-bold text-gray-800 group-hover:text-indigo-600 mb-2 truncate">{{ doc }}</h2>
                    <p class="text-sm text-gray-500">View summary and original content.</p>
                </a>
                {% endfor %}
            </div>
            
            {% if not docs %}
            <div class="text-center py-12 bg-white rounded-lg border border-dashed border-gray-300">
                <p class="text-gray-500">No documents found in <code>{{ doc_root }}</code></p>
            </div>
            {% endif %}
        </div>
    </body>
    </html>
    """
    return render_template_string(html, docs=docs, doc_root=DOC_ROOT)

# -----------------------------------------------------------------------------
# Document Viewer Routes
# -----------------------------------------------------------------------------

# 1. Accessing the Viewer Page
@app.route('/doc/<doc_name>/summary_html/')
@app.route('/doc/<doc_name>/summary_html/index.html')
def view_document(doc_name):
    # Serve the index.html generated by step8
    # We need to act as a static file server for this file
    path = DOC_ROOT / doc_name / "summary_html" / "index.html"
    if not path.exists():
        abort(404)
    return send_from_directory(path.parent, path.name)

# 2. Serving Static Assets (JS, CSS) for the Viewer
@app.route('/doc/<doc_name>/summary_html/static/<path:filename>')
def serve_viewer_static(doc_name, filename):
    path = DOC_ROOT / doc_name / "summary_html" / "static"
    return send_from_directory(path, filename)

# 3. Serving Data (summary.json)
@app.route('/doc/<doc_name>/summary_html/data/<path:filename>')
def serve_viewer_data(doc_name, filename):
    path = DOC_ROOT / doc_name / "summary_html" / "data"
    return send_from_directory(path, filename)

# 4. Serving Original Markdown Files (Referenced by Viewer)
# Step 7/8 structure assumes specific relative paths. 
# Viewer usually looks for `../section_markdown/xxx.md` relative to index.html location.
# In URL terms: `/doc/<doc_name>/section_markdown/<filename>`
@app.route('/doc/<doc_name>/section_markdown/<path:filename>')
def serve_markdown(doc_name, filename):
    path = DOC_ROOT / doc_name / "section_markdown"
    return send_from_directory(path, filename)

# 5. Serving Images
@app.route('/doc/<doc_name>/section_images/<path:filename>')
def serve_images(doc_name, filename):
    path = DOC_ROOT / doc_name / "section_images"
    return send_from_directory(path, filename)
    
# 6. Serving Original Output Assets (in case they are referenced differently)
@app.route('/doc/<doc_name>/output/<path:filename>')
def serve_output_alias(doc_name, filename):
    # This is a fallback/alias if needed
    path = DOC_ROOT / doc_name
    return send_from_directory(path, filename)


if __name__ == '__main__':
    if not DOC_ROOT.exists():
        print(f"Creating missing root directory: {DOC_ROOT}")
        DOC_ROOT.mkdir(parents=True, exist_ok=True)
        
    print(f"\n🚀 Server starting...")
    print(f"👉 Root: {DOC_ROOT}")
    print(f"👉 URL : http://localhost:{PORT}")
    print(f"----------------------------------------")
    
    app.run(host='0.0.0.0', port=PORT, debug=True)
