import os
import json
import logging
import re
from pathlib import Path
from tqdm import tqdm
from common_parameter import OUTPUT_DIR, LLM_MODEL, LLM_URL
from logger import setup_advanced_logger

import torch
torch.cuda.empty_cache()
os.environ['PYTORCH_ALLOC_CONF'] = 'expandable_segments:True'

logger = setup_advanced_logger(name="step7_summary_generator", log_dir=OUTPUT_DIR, log_level=logging.INFO)

# Configuration
MERGE_DEPTH_THRESHOLD = int(os.getenv("MERGE_DEPTH_THRESHOLD", 4))  # Depth > 2 (e.g. 1.1.1) will be merged into parent (1.1)
SUMMARY_MODEL = LLM_MODEL # Use from common_parameter
#SUMMARY_MODEL = "gemma3:12b" # Or user configured


class SummaryGenerator:
    def __init__(self):
        self.md_dir = Path(OUTPUT_DIR) / "section_markdown"
        self.out_dir = Path(OUTPUT_DIR) / "summary_html" / "data"
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self.sections = []
        self.section_pages = {}  # Map id -> {start, end}

    def load_sections(self):
        """Load all markdown files and parse section info"""
        # 1. Load Page Metadata from section_index.json (generated by step2)
        index_path = Path(OUTPUT_DIR) / "section_data_v2" / "section_index.json"
        if index_path.exists():
            try:
                with open(index_path, 'r', encoding='utf-8') as f:
                    idx_data = json.load(f)
                    # Load individual section files to get exact page ranges
                    for sec_entry in idx_data.get('sections', []):
                         sec_file = Path(OUTPUT_DIR) / "section_data_v2" / sec_entry['file']
                         if sec_file.exists():
                             with open(sec_file, 'r', encoding='utf-8') as sf:
                                 s_data = json.load(sf)
                                 self.section_pages[s_data['section_id']] = s_data['pages']
            except Exception as e:
                logger.error(f"Failed to load section index: {e}")

        if not self.md_dir.exists():
            logger.error(f"Markdown directory not found: {self.md_dir}")
            return

        files = sorted(list(self.md_dir.glob("*.md")))
        for f in files:
            # Filename format: {sort_idx:03d}_{clean_id}_{clean_title}.md
            # e.g. 001_1_Overview.md, 002_1_1_Scope.md
            match = re.match(r"(\d+)_([^_]+)_(.+)\.md", f.name)
            if not match:
                continue
                
            sort_idx = int(match.group(1))
            sec_id = match.group(2)
            title = match.group(3)
            
            # depth: count dots. "1"->1, "1.1"->2, "1.1.1"->3
            depth = sec_id.count('.') + 1
            
            # Read content
            with open(f, 'r', encoding='utf-8') as fr:
                content = fr.read()
                
            self.sections.append({
                "id": sec_id,
                "title": title,
                "sort_idx": sort_idx,
                "depth": depth,
                "content": content,
                "filename": f.name,
                "children": [],
                "merged_content": ""
            })
            
        # Sort just in case
        self.sections.sort(key=lambda x: x['sort_idx'])
        logger.info(f"Loaded {len(self.sections)} sections.")

    def organize_hierarchy_and_merge(self):
        """Organize flat list into hierarchy and prepare merged content for summary"""
        # Map by ID for easy lookup
        sec_map = {s['id']: s for s in self.sections}
        root_nodes = []
        
        # Build Tree
        for s in self.sections:
            parent_id = s['id'].rsplit('.', 1)[0] if '.' in s['id'] else None
            
            if parent_id and parent_id in sec_map:
                parent = sec_map[parent_id]
                parent['children'].append(s)
            else:
                # Top level or orphan
                root_nodes.append(s)
                
        # Merge Logic for Summary
        # We process linearly to accumulate content for summary targets
        
        summary_units = []
        current_unit = None
        
        for s in self.sections:
            # Determine if this section is a Summary Target (Depth <= THRESHOLD)
            if s['depth'] <= MERGE_DEPTH_THRESHOLD:
                # Close previous unit if exists
                if current_unit:
                    summary_units.append(current_unit)
                
                # Start new unit
                current_unit = {
                    "target_section": s,
                    "sub_sections": [],
                    "full_text": f"# {s['id']} {s['title']}\n\n{s['content']}\n\n"
                }
            else:
                # Append to current unit (if exists)
                if current_unit:
                    current_unit['sub_sections'].append(s)
                    current_unit['full_text'] += f"## {s['id']} {s['title']}\n\n{s['content']}\n\n"
        
        # Append last one
        if current_unit:
            summary_units.append(current_unit)
            
        return summary_units

    def clean_markdown_output(self, text):
        """Remove markdown code blocks if present"""
        if not text: return ""
        text = text.strip()
        # Remove ```markdown ... ``` or ``` ... ```
        if text.startswith("```"):
            # Remove first line
            lines = text.split('\n')
            if len(lines) > 1:
                # content is from line 1 to end-1 (if last line is ```)
                start = 1
                end = len(lines)
                if lines[-1].strip() == "```":
                    end -= 1
                return '\n'.join(lines[start:end]).strip()
            else:
                return text.strip('`') # malicious single line?
        return text

    def generate_summaries(self, summary_units):
        """Generate LLM summary for each unit"""
        results = []
        
        print(f"Generating summaries for {len(summary_units)} units...")
        
        # [Optimization] Load existing summaries to avoid re-generation
        existing_summaries = {}
        summary_json_path = self.out_dir / "summary.json"
        if summary_json_path.exists():
            try:
                with open(summary_json_path, 'r', encoding='utf-8') as f:
                    old_data = json.load(f)
                    
                    # Handle both list and dict formats
                    src_sections = old_data
                    if isinstance(old_data, dict) and 'sections' in old_data:
                        src_sections = old_data['sections']
                    
                    for sec in src_sections:
                        # Clean existing summary just in case
                        cleaned = self.clean_markdown_output(sec.get('summary', ''))
                        existing_summaries[sec['id']] = cleaned
                logger.info(f"Loaded {len(existing_summaries)} existing summaries for reuse.")
            except Exception as e:
                logger.warning(f"Could not load existing summaries: {e}")

        for unit in tqdm(summary_units):
            target = unit['target_section']
            full_text = unit['full_text']
            
            # Extract images from full_text to ensure they are safely passed to the viewer
            images_in_text = re.findall(r'!\[([^\]]*)\]\(([^)]+)\)', full_text)
            extracted_images = [{"title": match[0], "path": match[1]} for match in images_in_text]
            
            # [Optimization] Check cache first
            if target['id'] in existing_summaries:
                # logger.info(f"Skipping LLM for {target['id']} (Found in cache)")
                summary = existing_summaries[target['id']]
                
                # Append result immediately
                # Calculate page range for this unit (duplicate logic, could be refactored but keeping inline for minimal diff)
                relevant_ids = [target['id']] + [sub['id'] for sub in unit['sub_sections']]
                pages = set()
                for rid in relevant_ids:
                    if rid in self.section_pages:
                        p_info = self.section_pages[rid]
                        for p in range(p_info['start'], p_info['end'] + 1):
                            pages.add(p)
                if not pages: pages = {1}

                results.append({
                    "id": target['id'],
                    "title": target['title'],
                    "depth": target['depth'],
                    "summary": summary,
                    "original_md_file": target['filename'],
                    "sub_sections": [sub['id'] for sub in unit['sub_sections']],
                    "pages": sorted(list(pages)),
                    "extracted_images": extracted_images
                })
                continue

            
            # Skip if text is too short
            if len(full_text.strip()) < 50:
                summary = "Content is too short to summarize."
            else:
                # LLM Call
                prompt_base = (
                    f"당신은 기술 사양 문서를 요약하는 전문 테크니컬 라이터입니다.\n"
                    f"다음 내용(섹션 {target['id']} {target['title']} 및 그 하위 섹션)을 요약하십시오.\n"
                    f"핵심 요구 사항, 정의 및 아키텍처 세부 정보에 초점을 맞춰 간결하게 작성하십시오.\n"
                    f"중요한 수치 값이나 데이터는 절대 누락하지 마십시오.\n"
                    f"표(Table)의 텍스트 내용은 생략하지 말고 요약에 포함하되, 원본에 있는 링크(예: ![...](...)) 정보는 절대로 포함하지 마십시오.\n"
                    f"그림(Figure) 및 테이블(Table) 이미지는 시스템이 별도로 렌더링하므로, 요약문 텍스트 내에서 이미지 링크를 반환하지 마십시오.\n"
                    f"결과는 Markdown 형식으로 출력하십시오.\n"
                    f"중요: 텍스트를 마크다운 코드 블록(예: ```markdown)으로 감싸지 마십시오. 마크다운 내용만 직접 반환하십시오.\n\n"
                    f"내용:\n{full_text[:15000]}..." # Limit context size roughly
                )
                
                custom_prompt = os.getenv("USER_CUSTOM_PROMPT")
                if custom_prompt:
                    prompt = prompt_base + f"\n\n[사용자 추가 특별 요구사항]:\n{custom_prompt}"
                else:
                    prompt = prompt_base
                
                try:
                    # Using the sync _call_api from step1 logic style or just use LLMClient default
                    # LLMClient in lib_llm_client usually has chat method
                    # Let's assume simple completion/chat interface
                    # Adjust this call based on lib_llm_client.py implementation details we saw earlier or standard Ollama
                    
                    # Temporarily use requests directly if lib_llm_client isn't perfectly suited or check lib first
                    # For now, let's try a direct call similar to Qwen test
                    import requests
                    url = f"{LLM_URL}/api/generate"
                    payload = {
                        "model": "qwen2.5:32b", # Default summary model, adjust if needed
                        "prompt": prompt,
                        "stream": False,
                         "options": {"num_ctx": 16000}
                    }
                    # Fallback model check?
                    # Let's use a very basic one or what's available. 
                    # User mentioned qwen3-vl:8b/32b... maybe qwen2.5-coder or llama3.1?
                    # Let's assume 'llama3.1' or 'qwen2.5' is available for text summary. 
                    # If not, use 'qwen3-vl:32b-instruct-q4_K_M' (it can do text too).
                    payload['model'] = SUMMARY_MODEL
                    
                    resp = requests.post(url, json=payload, timeout=900)
                    raw_summary = resp.json().get('response', '')
                    summary = self.clean_markdown_output(raw_summary)
                    
                except Exception as e:
                    logger.error(f"Summary failed for {target['id']} (Model: {payload.get('model')}): {e}")
                    summary = "Summary generation failed."

            # Calculate page range for this unit
            # Combine pages of target and all subsections
            relevant_ids = [target['id']] + [sub['id'] for sub in unit['sub_sections']]
            pages = set()
            for rid in relevant_ids:
                if rid in self.section_pages:
                    p_info = self.section_pages[rid]
                    # Add all pages in range inclusive
                    for p in range(p_info['start'], p_info['end'] + 1):
                        pages.add(p)
            
            # Fallback if no pages found (unlikely if index loaded)
            if not pages:
                pages = {1}
                
            results.append({
                "id": target['id'],
                "title": target['title'],
                "depth": target['depth'],
                "summary": summary,
                "original_md_file": target['filename'],
                "sub_sections": [sub['id'] for sub in unit['sub_sections']],
                "pages": sorted(list(pages)),
                "extracted_images": extracted_images
            })

            # [Checkpoint] Save incomplete results periodically (every 5 items)
            if len(results) % 5 == 0:
                self.save_results(results)
                
        return results

    def save_results(self, summary_data):
        # Save structured JSON for Viewer
        
        # Infer title from PDF Path
        from common_parameter import PDF_PATH
        pdf_name = Path(PDF_PATH).stem
        # Clean title (remove underscores, etc if needed)
        doc_title = pdf_name.replace('_', ' ').replace('-', ' ')
        
        final_output = {
            "title": doc_title,
            "pdf_path": str(PDF_PATH), # Store original path for Server to resolve
            "sections": summary_data
        }
        
        out_file = self.out_dir / "summary.json"
        with open(out_file, 'w', encoding='utf-8') as f:
            json.dump(final_output, f, indent=2)
        msg = f"Saved summary data to {out_file}"
        tqdm.write(msg)
        logger.debug(msg)

    def process(self):
        self.load_sections()
        units = self.organize_hierarchy_and_merge()
        summaries = self.generate_summaries(units)
        self.save_results(summaries)

if __name__ == "__main__":
    import time
    start_time = time.time()
    gen = SummaryGenerator()
    gen.process()
    end_time = time.time()
    logger.info(f"Total Summary Generation Time: {end_time - start_time:.2f} seconds")
